### 번역

1. **Now of course things can also go wrong**  
   **when sending a request.**  
   요청을 보낼 때 문제가 발생할 수도 있습니다.

2. **For example, there might be no internet connection,**  
   **it temporarily went away.**  
   예를 들어, 인터넷 연결이 없거나  
   일시적으로 끊어질 수 있습니다.

3. **That's one possibility.**  
   이는 가능성 중 하나입니다.

4. **But there also might be something wrong with our backend**  
   **and an error might occur on that backend.**  
   하지만 백엔드에 문제가 있거나  
   백엔드에서 오류가 발생할 수도 있습니다.

5. **And to simulate that,**  
   **I will actually return a different response here**  
   **after this delay.**  
   이를 시뮬레이션하기 위해,  
   이 지연 이후 다른 응답을 반환하겠습니다.

6. **Temporarily, I'll get rid of it later,**  
   **but for now I wanna return a response**  
   **that sets a status code of 500.**  
   이는 일시적인 설정이며 나중에 제거하겠지만,  
   현재는 상태 코드 500의 응답을 반환하고자 합니다.

7. **And that's how you can do this in Node and Express.**  
   Node와 Express에서 이렇게 구현할 수 있습니다.

8. **This creates a response with a status code of 500,**  
   **and I'll call the json method on that**  
   **to then really finalize that response,**  
   **so to say.**  
   이는 상태 코드 500의 응답을 생성하고,  
   `json` 메서드를 호출하여  
   응답을 완전히 완료합니다.

9. **So now this route will no longer return the places,**  
   **but instead this error response,**  
   **and of course nobody would do that,**  
   **but for simulating the error use case, this is perfect.**  
   이제 이 라우트는 장소 데이터를 반환하지 않고  
   오류 응답을 반환합니다.  
   물론 실제로 이렇게 하진 않겠지만,  
   오류 상황을 시뮬레이션하는 데는 적합합니다.

10. **You now just have to go back to that terminal**  
    **where you started your backend development server**  
    **and quit it by pressing Ctrl C**  
    **and restart it**  
    **so that those code changes are picked up.**  
    백엔드 개발 서버를 실행했던 터미널로 돌아가  
    `Ctrl + C`를 눌러 종료한 뒤,  
    서버를 다시 시작하여 코드 변경 사항을 적용하세요.

11. **With that, if you now reload,**  
    **you'll see that we're fetching those places**  
    **and then they never arrive.**  
    이제 새로고침하면  
    장소 데이터를 가져오는 중인데  
    도착하지 않는 것을 볼 수 있습니다.

12. **And we see an error here in the developer tools**  
    **that we got some HTTP related error.**  
    개발자 도구에서 HTTP 관련 오류가 발생한 것을  
    확인할 수 있습니다.

13. **Well, how can we now handle that in our component?**  
    이제 컴포넌트에서 이를 어떻게 처리할 수 있을까요?

14. **Well, for example, again, by adding an extra signal,**  
    **an error signal for example,**  
    **though the name of course is up to you.**  
    예를 들어, 추가적으로 `error`라는 Signal을  
    생성할 수 있습니다.  
    물론 이름은 원하는 대로 설정할 수 있습니다.

15. **And that could store a string value.**  
    **So the error message.**  
    이 Signal은 문자열 값을 저장할 수 있으며,  
    여기서는 오류 메시지를 저장합니다.

16. **And initially that could be an empty string since initially**  
    **we don't have any error.**  
    초기에는 오류가 없으므로 빈 문자열로 설정할 수 있습니다.

17. **But then I wanna set this signal**  
    **to the error message if an error occurs here.**  
    하지만 오류가 발생하면  
    이 Signal을 해당 오류 메시지로 설정합니다.

18. **And for that, we can add that third**  
    **and last function to our observer object,**  
    **the error function, which will be triggered**  
    **whenever some error is thrown somewhere**  
    **in that observable chain.**  
    이를 위해 Observer 객체에  
    세 번째 함수인 `error` 함수를 추가할 수 있습니다.  
    이 함수는 Observable 체인에서 오류가 발생할 때마다  
    트리거됩니다.

19. **And Angular will produce an error**  
    **if something goes wrong technically,**  
    **so if we have no internet connection for example,**  
    **or if we get an error response.**  
    Angular는 기술적으로 문제가 발생할 경우  
    오류를 생성합니다.  
    예를 들어, 인터넷 연결이 없거나  
    오류 응답을 받을 때 발생합니다.

20. **In both cases, Angular will produce an error value**  
    **and this function will get triggered**  
    **and it will receive that error information then.**  
    두 경우 모두 Angular는 오류 값을 생성하며,  
    이 함수가 트리거되고 해당 오류 정보를 받게 됩니다.

21. **So in here, we could then use our error signal**  
    **and set it to that error we're getting here.**  
    여기서 `error` Signal을 사용하여  
    발생한 오류를 해당 Signal에 설정할 수 있습니다.

22. **It's worth noting that TypeScript doesn't know what type**  
    **of value we'll get here though.**  
    그러나 TypeScript는 이곳에서  
    어떤 유형의 값을 받을지 알지 못합니다.

23. **Nonetheless, we can try setting it like this**  
    **and then we can of course go back**  
    **to the available places template and add another check here**  
    **and also update this first check**  
    **because now here we can check if we're fetching**  
    **and error is falsey.**  
    그래도 이렇게 값을 설정할 수 있으며,  
    이후 `available-places` 템플릿으로 돌아가  
    새 조건을 추가하고,  
    첫 번째 조건도 업데이트할 수 있습니다.  
    이제 데이터를 가져오는 중인지와  
    `error`가 비어 있는지를 확인할 수 있습니다.

24. **So this error signal produces a falsey value.**  
    **In that case, I wanna show this loading text,**  
    **but otherwise if we're not fetching**  
    **or we have an error, I don't want to show that.**  
    `error` Signal이 비어 있는 값을 생성하면  
    로딩 텍스트를 표시하고,  
    데이터를 가져오지 않거나 오류가 있으면  
    이를 표시하지 않도록 설정합니다.

25. **And instead we can add another if check here**  
    **and check if error produces a truthy value,**  
    **so if the error signal has a non empty string,**  
    **and in that case I want to output a paragraph with the class**  
    **fallback-text on it,**  
    **that will output that error message.**  
    그리고 또 다른 `if` 조건을 추가하여  
    `error`가 참 값을 생성하는지 확인합니다.  
    즉, `error` Signal이 비어 있지 않은 문자열을  
    가지고 있다면,  
    `fallback-text` 클래스를 가진 단락에  
    오류 메시지를 출력하도록 설정합니다.

26. **So we can use string interpolation**  
    **to output the value stored in the error signal.**  
    문자열 보간법을 사용하여  
    `error` Signal에 저장된 값을 출력할 수 있습니다.

27. **And if you save that all and you reload, you'll see that**  
    **after a while you get this object Object thing here.**  
    이를 저장하고 새로 고침하면,  
    잠시 후 객체(Object) 형태의 내용이 출력됩니다.

28. **And we're getting this**  
    **because this error we're getting here**  
    **in this error function,**  
    **this argument here is actually not**  
    **an error message.**  
    이는 `error` 함수에서 받은 오류가  
    실제로는 오류 메시지가 아니기 때문에 발생합니다.

29. **Instead it's an error object,**  
    **which however should contain a message property.**  
    대신 이 값은 `message` 속성을 포함하는  
    오류 객체입니다.

30. **So we can try accessing it like this.**  
    따라서 이를 다음과 같이  
    접근해 볼 수 있습니다.

31. **And with that, if we reload,**  
    **we can again try fetching those places and**  
    **after a while we get some message,**  
    **however, not really a user-friendly message.**  
    이렇게 설정한 후 새로 고침하면,  
    다시 장소 데이터를 가져오려고 시도할 수 있으며,  
    잠시 후 메시지가 표시됩니다.  
    하지만 사용자 친화적인 메시지는 아닙니다.

32. **So what we might wanna do instead is maybe log**  
    **that error for ourselves,**  
    **but show a more user-friendly message here.**  
    따라서 오류를 로깅하여 확인하면서  
    사용자에게는 더 친화적인 메시지를  
    표시하는 것이 좋습니다.

33. **And we could of course do that**  
    **by simply console logging the error here.**  
    이는 단순히 오류를  
    콘솔에 로깅하는 방식으로  
    구현할 수 있습니다.

34. **Or alternatively, we could try sending it**  
    **to some analytics server if we had any.**  
    또는, 분석 서버가 있다면  
    해당 서버로 오류를 전송할 수도 있습니다.

35. **Here, I'll just log it**  
    **and then maybe output some hardcoded message like**  
    **"Something went wrong**  
    **fetching the available places.**  
    **Please try again later."**  
    여기서는 오류를 콘솔에 로깅한 뒤,  
    "장소 데이터를 가져오는 중 오류가 발생했습니다.  
    나중에 다시 시도해주세요."와 같은  
    하드코딩된 메시지를 출력하도록 하겠습니다.

36. **That is something we could do here.**  
    이를 이곳에서 구현할 수 있습니다.

37. **And if we save that**  
    **and we reload, we should see that**  
    **more user-friendly message here.**  
    이를 저장하고 새로 고침하면,  
    사용자 친화적인 메시지가 표시됩니다.

38. **And we still log that error object here,**  
    **which now contains more details about the error.**  
    또한 오류 객체가 여전히 콘솔에 로깅되며,  
    해당 객체에는 오류에 대한 세부 정보가 포함됩니다.

아직 남은 부분이 있습니다. 계속 번역해 드리겠습니다.

---

39. **But again, we could also use an operator here,**  
    **not because we have to,**  
    **but because we can, to keep these observer functions leaner.**  
    그러나 반드시 필요한 것은 아니지만,  
    옵저버 함수를 더 간결하게 유지하기 위해  
    연산자를 사용할 수도 있습니다.

40. **And therefore we can add a second argument**  
    **to this pipe method.**  
    따라서 `pipe` 메서드에 두 번째 인수를 추가할 수 있습니다.

41. **And after adding this map operator,**  
    **we can add the catchError operator,**  
    **which is another operator that's imported from RxJS.**  
    `map` 연산자를 추가한 후,  
    RxJS에서 가져온 또 다른 연산자인  
    `catchError` 연산자를 추가할 수 있습니다.

42. **And catchError does**  
    **what its name implies.**  
    **It in the end is responsible**  
    **for handling errors,**  
    **and for potentially transforming errors.**  
    `catchError`는 이름 그대로 오류를 처리하며,  
    오류를 변환할 수도 있습니다.

43. **For that, it takes a function just like map.**  
    이를 위해 `map`처럼 함수를 받습니다.

44. **And that function takes an argument, a parameter,**  
    **which in the end is that error that we got.**  
    해당 함수는 인수로 오류 객체를 받습니다.

45. **It actually also takes a second argument,**  
    **which is that observable that emitted that error.**  
    또한 오류를 발행한 Observable을  
    두 번째 인수로 받을 수도 있습니다.

46. **But here I only care about the error.**  
    그러나 여기서는 오류에만 관심이 있습니다.

47. **And then catchError actually needs**  
    **to return a new observable.**  
    `catchError`는 새 Observable을 반환해야 합니다.

48. **So unlike map, it should now not return some data**  
    **to which this error has been converted,**  
    **but instead it must return a new observable.**  
    따라서 `map`과는 달리,  
    변환된 데이터를 반환하는 대신  
    새 Observable을 반환해야 합니다.

49. **And I'll generate a new observable here**  
    **by calling throwError,**  
    **which is another function**  
    **that must be imported from RxJS as well.**  
    여기서 RxJS에서 가져온 `throwError`를 호출하여  
    새 Observable을 생성하겠습니다.

50. **But throwError is now not an operator**  
    **that you would add to pipe,**  
    **but instead like interval**  
    **before it's an operator,**  
    **a function that generates a new observable,**  
    **but it will generate an observable which will automatically**  
    **throw an error again, which is a behavior I want here**  
    **so that this error function of the observer gets triggered.**  
    `throwError`는 `pipe`에 추가하는 연산자가 아니라  
    `interval`처럼 새 Observable을 생성하는 함수입니다.  
    이 함수는 오류를 자동으로 다시 발생시키는  
    Observable을 생성하며,  
    이를 통해 Observer의 `error` 함수가  
    트리거되도록 합니다.

51. **But now we can configure that error**  
    **that will be thrown here.**  
    이제 발생할 오류를 구성할 수 있습니다.

52. **And for that we need to pass another function**  
    **to throwError.**  
    이를 위해 `throwError`에  
    또 다른 함수를 전달해야 합니다.

53. **So lots of nested functions here, I know,**  
    **but this function now should return an error object**  
    **or anything which you want to throw as an error.**  
    여기서 많은 중첩 함수가 사용되지만,  
    이 함수는 오류 객체 또는  
    오류로 던질 내용을 반환해야 합니다.

54. **But here I'll generate a new error object**  
    **using the built-in Error class,**  
    **the built-in error constructor**  
    **that's built into JavaScript.**  
    여기서는 JavaScript의 내장 `Error` 클래스를 사용하여  
    새 오류 객체를 생성하겠습니다.

55. **And here you can pass an error message to this**  
    **so that you generate an error object which has this message**  
    **which you pass to the constructor attached to it.**  
    생성자에 오류 메시지를 전달하면,  
    해당 메시지가 포함된 오류 객체를 생성할 수 있습니다.

56. **And I'll grab my message from down here**  
    **and use that here as a value forwarded to the error constructor.**  
    아래에서 메시지를 가져와  
    오류 생성자에 전달할 값으로 사용하겠습니다.

57. **And that's now how we can transform this error.**  
    이것이 오류를 변환하는 방법입니다.

58. **We can now still log that original error here**  
    **if we want to.**  
    필요하다면 원래 오류를  
    이곳에서 로그로 출력할 수도 있습니다.

59. **For that, we just need curly braces now,**  
    **since I now have multi-line code**  
    **and not just one statement, not just one expression here,**  
    **and we need to return the thrown error.**  
    이제 여러 줄의 코드를 사용하므로  
    중괄호를 추가하고,  
    던진 오류를 반환해야 합니다.

60. **But with that we transformed the error and logged it.**  
    이렇게 하면 오류를 변환하고 로그로 출력했습니다.

61. **And down here in that error observer function,**  
    **we can now log error.message as before.**  
    아래의 `error` Observer 함수에서  
    이전처럼 `error.message`를 로그로 출력할 수 있습니다.

62. **We can also add a type annotation here**  
    **and make it clear that this will be of type error**  
    **so that it will be such an error object.**  
    여기에 타입 주석을 추가하여  
    이 값이 `Error` 타입의 객체임을 명확히 할 수 있습니다.

63. **And since those objects have message properties,**  
    **we can safely access message here.**  
    이러한 객체에는 `message` 속성이 있으므로  
    안전하게 접근할 수 있습니다.

64. **And again, just as with map, you don't need this operator.**  
    **It does make things more complex here,**  
    **but you will see it in some Angular projects.**  
    `map`과 마찬가지로, 이 연산자는 필수가 아닙니다.  
    다소 복잡해질 수 있지만,  
    몇몇 Angular 프로젝트에서는 이를 볼 수 있습니다.

65. **It can be useful**  
    **for getting your error transformation logic**  
    **out of the observer functions,**  
    **which you typically should try to keep clean and lean**  
    **and therefore I wanted to cover it here as well.**  
    Observer 함수에서 오류 변환 로직을 분리하는 데  
    유용할 수 있습니다.  
    Observer 함수는 일반적으로 간결하고 깔끔하게  
    유지해야 하므로, 이를 설명하고자 했습니다.

66. **With all that done, the behavior should be**  
    **the same as before.**  
    이 모든 작업이 완료되면  
    동작은 이전과 동일할 것입니다.

67. **We see the loading fallback and then**  
    **after a while we see that human friendly error message**  
    **and we log the error object to the console.**  
    로딩 중 대체 텍스트가 표시되고,  
    잠시 후 사용자 친화적인 오류 메시지가 표시되며,  
    오류 객체가 콘솔에 로그로 출력됩니다.

68. **And with that all done,**  
    **I'll get rid of that error in the backend code**  
    **and comment out this line since I of course only wanted**  
    **to show this error handling for demo purposes.**  
    이제 백엔드 코드에서 오류를 제거하고,  
    데모 목적으로 추가했던 줄을 주석 처리하겠습니다.

69. **So with that commented out,**  
    **we should restart that backend server**  
    **so that the updated code is picked up.**  
    이 줄을 주석 처리한 뒤,  
    백엔드 서버를 재시작하여  
    업데이트된 코드가 적용되도록 해야 합니다.

70. **And with that, if you now reload,**  
    **you should see that the places are fetched**  
    **and displayed successfully again.**  
    이제 새로 고침하면 장소 데이터를 정상적으로 가져와  
    화면에 표시되는 것을 확인할 수 있습니다.

71. **And that's how you can handle error**  
    **and loading states in Angular**  
    **when working with HTTP requests.**  
    이것이 Angular에서 HTTP 요청을 처리할 때  
    오류 및 로딩 상태를 다루는 방법입니다.

---

### 번역이 완료되었습니다! 😊
다른 요청이나 질문이 있다면 언제든 말씀해 주세요!
